"""initial schema

Revision ID: dd906b116ed2
Revises: 
Create Date: 2026-07-27 13:03:56.879504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd906b116ed2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('study_type', sa.String(), nullable=True),
    sa.Column('marine_relevance_status', sa.String(), nullable=False),
    sa.Column('molecular_relevance_status', sa.String(), nullable=False),
    sa.Column('canonical_status', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('study_id')
    )
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('code_version', sa.String(), nullable=True),
    sa.Column('model_config_snapshot', sa.JSON(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('schema_versions', sa.JSON(), nullable=True),
    sa.Column('sources_queried', sa.JSON(), nullable=True),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('new_studies', sa.Integer(), nullable=False),
    sa.Column('updated_studies', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('manual_review_items', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('candidate_matches',
    sa.Column('candidate_match_id', sa.String(), nullable=False),
    sa.Column('study_a_id', sa.String(), nullable=False),
    sa.Column('study_b_id', sa.String(), nullable=True),
    sa.Column('candidate_record_ref', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('supporting_features', sa.JSON(), nullable=True),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('reviewer_decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['study_a_id'], ['studies.study_id'], ),
    sa.ForeignKeyConstraint(['study_b_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('candidate_match_id')
    )
    op.create_index(op.f('ix_candidate_matches_study_a_id'), 'candidate_matches', ['study_a_id'], unique=False)
    op.create_index(op.f('ix_candidate_matches_study_b_id'), 'candidate_matches', ['study_b_id'], unique=False)
    op.create_table('entities',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('entity_level', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('parent_entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_entities_study_id'), 'entities', ['study_id'], unique=False)
    op.create_table('external_identifiers',
    sa.Column('identifier_id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('identifier_type', sa.String(), nullable=False),
    sa.Column('identifier_value', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('identifier_id'),
    sa.UniqueConstraint('identifier_type', 'identifier_value', 'study_id', name='uq_identifier_type_value_study')
    )
    op.create_index(op.f('ix_external_identifiers_identifier_value'), 'external_identifiers', ['identifier_value'], unique=False)
    op.create_index(op.f('ix_external_identifiers_study_id'), 'external_identifiers', ['study_id'], unique=False)
    op.create_table('publications',
    sa.Column('publication_id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('pmid', sa.String(), nullable=True),
    sa.Column('pmcid', sa.String(), nullable=True),
    sa.Column('openalex_id', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('open_access_status', sa.String(), nullable=False),
    sa.Column('fulltext_available', sa.Boolean(), nullable=False),
    sa.Column('relationship_to_study', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('publication_id')
    )
    op.create_index(op.f('ix_publications_doi'), 'publications', ['doi'], unique=False)
    op.create_index(op.f('ix_publications_openalex_id'), 'publications', ['openalex_id'], unique=False)
    op.create_index(op.f('ix_publications_pmcid'), 'publications', ['pmcid'], unique=False)
    op.create_index(op.f('ix_publications_pmid'), 'publications', ['pmid'], unique=False)
    op.create_index(op.f('ix_publications_study_id'), 'publications', ['study_id'], unique=False)
    op.create_table('source_watermarks',
    sa.Column('watermark_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('query_identifier', sa.String(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_cursor', sa.String(), nullable=True),
    sa.Column('last_run_id', sa.String(), nullable=True),
    sa.Column('overlap_window_days', sa.Integer(), nullable=False),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_run_id'], ['workflow_runs.run_id'], ),
    sa.PrimaryKeyConstraint('watermark_id'),
    sa.UniqueConstraint('source_name', 'query_identifier', name='uq_source_watermark_query')
    )
    op.create_table('sources',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('external_identifier', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('access_status', sa.String(), nullable=False),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('is_mirror', sa.Boolean(), nullable=False),
    sa.Column('mirror_group', sa.String(), nullable=True),
    sa.Column('source_version', sa.String(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('inspection_status', sa.String(), nullable=False),
    sa.Column('inspection_level', sa.String(), nullable=False),
    sa.Column('parent_source_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_source_id'], ['sources.source_id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_sources_external_identifier'), 'sources', ['external_identifier'], unique=False)
    op.create_index(op.f('ix_sources_mirror_group'), 'sources', ['mirror_group'], unique=False)
    op.create_index(op.f('ix_sources_study_id'), 'sources', ['study_id'], unique=False)
    op.create_table('data_assets',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('repository', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('access_status', sa.String(), nullable=False),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('raw_or_processed', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('n_samples_reported', sa.Integer(), nullable=True),
    sa.Column('n_samples_observed', sa.Integer(), nullable=True),
    sa.Column('n_features_reported', sa.Integer(), nullable=True),
    sa.Column('n_features_observed', sa.Integer(), nullable=True),
    sa.Column('feature_type', sa.String(), nullable=True),
    sa.Column('matrix_orientation', sa.String(), nullable=True),
    sa.Column('taxonomy_available', sa.Boolean(), nullable=True),
    sa.Column('environmental_metadata_available', sa.Boolean(), nullable=True),
    sa.Column('sample_metadata_available', sa.Boolean(), nullable=True),
    sa.Column('inspection_level', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_data_assets_entity_id'), 'data_assets', ['entity_id'], unique=False)
    op.create_index(op.f('ix_data_assets_study_id'), 'data_assets', ['study_id'], unique=False)
    op.create_table('missingness',
    sa.Column('missingness_id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('target_schema', sa.String(), nullable=False),
    sa.Column('target_field', sa.String(), nullable=False),
    sa.Column('missingness_status', sa.String(), nullable=False),
    sa.Column('sources_inspected', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('missingness_id')
    )
    op.create_index(op.f('ix_missingness_entity_id'), 'missingness', ['entity_id'], unique=False)
    op.create_index(op.f('ix_missingness_study_id'), 'missingness', ['study_id'], unique=False)
    op.create_table('raw_facts',
    sa.Column('fact_id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_locator', sa.String(), nullable=True),
    sa.Column('raw_field_name', sa.String(), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_text_value', sa.Text(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('fact_type_candidate', sa.String(), nullable=True),
    sa.Column('entity_level', sa.String(), nullable=True),
    sa.Column('support_type', sa.String(), nullable=False),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.Column('extractor_version', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('confidence_metadata', sa.JSON(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_raw_facts_entity_id'), 'raw_facts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_raw_facts_fact_type_candidate'), 'raw_facts', ['fact_type_candidate'], unique=False)
    op.create_index(op.f('ix_raw_facts_source_id'), 'raw_facts', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_facts_study_id'), 'raw_facts', ['study_id'], unique=False)
    op.create_table('source_relationships',
    sa.Column('source_relationship_id', sa.String(), nullable=False),
    sa.Column('from_source_id', sa.String(), nullable=False),
    sa.Column('to_source_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_source_id'], ['sources.source_id'], ),
    sa.ForeignKeyConstraint(['to_source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('source_relationship_id')
    )
    op.create_index(op.f('ix_source_relationships_from_source_id'), 'source_relationships', ['from_source_id'], unique=False)
    op.create_index(op.f('ix_source_relationships_to_source_id'), 'source_relationships', ['to_source_id'], unique=False)
    op.create_table('standardized_values',
    sa.Column('standardized_value_id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('target_schema', sa.String(), nullable=False),
    sa.Column('target_schema_version', sa.String(), nullable=False),
    sa.Column('target_field', sa.String(), nullable=False),
    sa.Column('standardized_value', sa.Text(), nullable=True),
    sa.Column('controlled_term_id', sa.String(), nullable=True),
    sa.Column('mapping_method', sa.String(), nullable=False),
    sa.Column('validation_status', sa.String(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('standardized_value_id')
    )
    op.create_index(op.f('ix_standardized_values_entity_id'), 'standardized_values', ['entity_id'], unique=False)
    op.create_index(op.f('ix_standardized_values_study_id'), 'standardized_values', ['study_id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('idempotency_key', name='uq_task_idempotency_key')
    )
    op.create_index(op.f('ix_tasks_available_after'), 'tasks', ['available_after'], unique=False)
    op.create_index(op.f('ix_tasks_idempotency_key'), 'tasks', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_study_id'), 'tasks', ['study_id'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_table('standardized_value_evidence',
    sa.Column('standardized_value_id', sa.String(), nullable=False),
    sa.Column('fact_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['raw_facts.fact_id'], ),
    sa.ForeignKeyConstraint(['standardized_value_id'], ['standardized_values.standardized_value_id'], ),
    sa.PrimaryKeyConstraint('standardized_value_id', 'fact_id')
    )
    op.create_table('validation_results',
    sa.Column('validation_result_id', sa.String(), nullable=False),
    sa.Column('study_id', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('fact_id', sa.String(), nullable=True),
    sa.Column('standardized_value_id', sa.String(), nullable=True),
    sa.Column('validator_name', sa.String(), nullable=False),
    sa.Column('validator_version', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('compared_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['fact_id'], ['raw_facts.fact_id'], ),
    sa.ForeignKeyConstraint(['standardized_value_id'], ['standardized_values.standardized_value_id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ),
    sa.PrimaryKeyConstraint('validation_result_id')
    )
    op.create_index(op.f('ix_validation_results_study_id'), 'validation_results', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_study_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_table('standardized_value_evidence')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_study_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_idempotency_key'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_available_after'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_standardized_values_study_id'), table_name='standardized_values')
    op.drop_index(op.f('ix_standardized_values_entity_id'), table_name='standardized_values')
    op.drop_table('standardized_values')
    op.drop_index(op.f('ix_source_relationships_to_source_id'), table_name='source_relationships')
    op.drop_index(op.f('ix_source_relationships_from_source_id'), table_name='source_relationships')
    op.drop_table('source_relationships')
    op.drop_index(op.f('ix_raw_facts_study_id'), table_name='raw_facts')
    op.drop_index(op.f('ix_raw_facts_source_id'), table_name='raw_facts')
    op.drop_index(op.f('ix_raw_facts_fact_type_candidate'), table_name='raw_facts')
    op.drop_index(op.f('ix_raw_facts_entity_id'), table_name='raw_facts')
    op.drop_table('raw_facts')
    op.drop_index(op.f('ix_missingness_study_id'), table_name='missingness')
    op.drop_index(op.f('ix_missingness_entity_id'), table_name='missingness')
    op.drop_table('missingness')
    op.drop_index(op.f('ix_data_assets_study_id'), table_name='data_assets')
    op.drop_index(op.f('ix_data_assets_entity_id'), table_name='data_assets')
    op.drop_table('data_assets')
    op.drop_index(op.f('ix_sources_study_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_mirror_group'), table_name='sources')
    op.drop_index(op.f('ix_sources_external_identifier'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('source_watermarks')
    op.drop_index(op.f('ix_publications_study_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_pmid'), table_name='publications')
    op.drop_index(op.f('ix_publications_pmcid'), table_name='publications')
    op.drop_index(op.f('ix_publications_openalex_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_doi'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_external_identifiers_study_id'), table_name='external_identifiers')
    op.drop_index(op.f('ix_external_identifiers_identifier_value'), table_name='external_identifiers')
    op.drop_table('external_identifiers')
    op.drop_index(op.f('ix_entities_study_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_candidate_matches_study_b_id'), table_name='candidate_matches')
    op.drop_index(op.f('ix_candidate_matches_study_a_id'), table_name='candidate_matches')
    op.drop_table('candidate_matches')
    op.drop_table('workflow_runs')
    op.drop_table('studies')
    # ### end Alembic commands ###
